"""
normalizer/config.py — Extraction patterns and LLM configuration.

Column names are determined dynamically from section_freq.json generated by triage.py.
"""
from __future__ import annotations

import re

# Structural titles excluded from the output matrix (no useful content)
SKIP_TITLES: set[str] = {
    "OPENING", "CLOSING", "UNTITLED",
}

# ─── Product code extraction from filename ────────────────────────────────────
# Covers common alphanumeric product code patterns:
#   Single-letter prefix: A-01, E-7001, B-CU-12
#   Multi-letter prefix:  AB-05, BEQ-15
#   Compact codes:        HM134, DVT603
CODE_PATTERN = re.compile(
    r"\b(?:"
    r"[A-Z]{1,6}-[A-Z0-9]{2,}(?:-[A-Z0-9]+)*"
    r"|[A-Z]{2,8}\d{2,}"
    r")\b"
)

# Filename prefixes that are not product codes (generic document type labels)
_FILENAME_NOISE = re.compile(
    r"(?i)^(?:instructions?|manual|guide|datasheet|specification|protocol)\s+(?:for\s+)?",
)

# If more than this many codes are found → multi-product document → code=None
MAX_PRODUCT_CODES: int = 3

# ─── LLM ─────────────────────────────────────────────────────────────────────
# Backend to use: "claude" | "ollama" | "none"
LLM_BACKEND: str = "ollama"

# Model per backend
LLM_MODELS: dict[str, str] = {
    "claude": "claude-haiku-4-5-20251001",
    "ollama": "mistral",
}

OLLAMA_URL: str = "http://localhost:11434/api/chat"

# Low temperature: classification task, not creative generation
LLM_TEMPERATURE: float = 0.0
