"""
normalizer/router.py — Normalizer pipeline orchestrator.

Full flow:
  1. Read section_freq.json (generated by triage.py).
  2. If an LLM backend is available, call the LLM ONCE to group section titles
     into canonical semantic columns and generate the mapping
     {normalized_title → column}. The result is saved to section_columns_map.json
     and reused on subsequent runs (unless --force is used).
  3. Without LLM, columns are determined by frequency alone (fallback).
  4. Read triage_control.json and process each eligible document:
       - Call build_row() using the corpus map to resolve most sections
         without an additional LLM call.
       - Only sections not covered by the map go to the per-document LLM.
  5. Generate output_normalizado/<stem>.json per document and the final Excel.
"""
from __future__ import annotations

import json
from collections import Counter
from pathlib import Path
from typing import Any

from normalizer.assembler import build_column_map_prompt, parse_llm_json
from normalizer.client import LLMClient
from normalizer.exporter import rows_to_excel
from normalizer.mapper import build_row


# ─── Prompt export (no-API workflow) ─────────────────────────────────────────

def export_column_map_prompt(
    control_path: Path | str = "triage_control.json",
    output_file:  Path | str | None = None,
) -> None:
    """Export the corpus-level prompt to a text file for manual LLM use.

    Workflow:
      1. python normalize.py --export-prompt
      2. Copy the contents of column_map_prompt.txt
      3. Paste into any LLM chat interface → copy the JSON response
      4. Save the response as section_columns_map.json
         in the same folder as triage_control.json
      5. python normalize.py   (no --backend; map will be loaded from disk)
    """
    control_path = Path(control_path)
    freq_path    = control_path.parent / "section_freq.json"

    if not freq_path.exists():
        print(f"[normalizer] {freq_path} not found. Run run_triage() first.")
        return

    with open(freq_path, encoding="utf-8") as f:
        freq_data = json.load(f)

    sections = [
        s for s in freq_data.get("sections", [])
        if s["docs_con_seccion"] >= 2
        and s["normalized_title"].strip() not in _STRUCTURAL
        and not s.get("es_estructural", False)
    ]
    total_docs = freq_data.get("total_docs", 0)

    system, user = build_column_map_prompt(sections, total_docs)

    full_prompt = (
        "=== ASSISTANT INSTRUCTIONS ===\n"
        + system
        + "\n\n=== CORPUS DATA ===\n"
        + user
    )

    if output_file is None:
        output_file = control_path.parent / "column_map_prompt.txt"
    output_file = Path(output_file)
    output_file.parent.mkdir(parents=True, exist_ok=True)
    output_file.write_text(full_prompt, encoding="utf-8")

    map_path = control_path.parent / "section_columns_map.json"

    print(f"\n[normalizer] Prompt exported to: {output_file}")
    print("\nSteps to continue without API:")
    print(f"  1. Open: {output_file}")
    print("  2. Copy all content and paste into any LLM chat interface.")
    print("  3. Copy the full JSON response from the LLM.")
    print(f"  4. Save it as: {map_path}")
    print('     The JSON must have this structure:')
    print('     { "columns": ["col1", "col2", ...],')
    print('       "title_map": { "section_title": "col1", ... } }')
    print("  5. Run: python normalize.py")
    print("     (no --backend; the map will be loaded from disk)\n")


# Eligible actions for normalization
_ACCIONES_PROCESAR = {"process", "process_primary_language"}

# Normalized titles that should never be columns (structural markers)
_STRUCTURAL = {"other", "opening", "closing", "untitled",
               "OPENING", "CLOSING", "UNTITLED"}


# ─── Column determination ─────────────────────────────────────────────────────

def determine_columns_with_llm(
    freq_data: dict,
    llm_client: LLMClient,
    map_path: Path,
    min_docs: int = 2,
) -> tuple[list[str], dict[str, str]]:
    """Call the LLM to group section titles into canonical columns.

    Filters sections with at least min_docs documents that are not structural.
    Saves the result to map_path for reuse.

    Returns:
        (columns, title_map) where title_map = {normalized_title: column}.
    """
    sections = [
        s for s in freq_data.get("sections", [])
        if s["docs_con_seccion"] >= min_docs
        and s["normalized_title"].strip() not in _STRUCTURAL
        and not s.get("es_estructural", False)
    ]

    total_docs = freq_data.get("total_docs", 0)
    print(f"[normalizer] Calling LLM to determine columns "
          f"({len(sections)} section titles, {total_docs} docs)…")

    system, user = build_column_map_prompt(sections, total_docs)
    raw = llm_client.complete(system, user, max_tokens=2048)
    parsed = parse_llm_json(raw)

    columns: list[str] = parsed.get("columns", [])
    title_map: dict[str, str] = parsed.get("title_map", {})

    title_map = {str(k).strip(): str(v).strip() for k, v in title_map.items()}
    columns = [str(c).strip() for c in columns if str(c).strip()]

    if "additional_content" not in columns:
        columns.append("additional_content")

    _MAX_COLUMNS = 12
    if len(columns) > _MAX_COLUMNS:
        _original_count = len(columns)
        col_usage = Counter(title_map.values())
        non_fallback = [c for c in columns if c != "additional_content"]
        non_fallback = sorted(non_fallback, key=lambda c: -col_usage.get(c, 0))
        non_fallback = non_fallback[:_MAX_COLUMNS - 1]
        kept = set(non_fallback) | {"additional_content"}
        columns = non_fallback + ["additional_content"]
        title_map = {
            k: (v if v in kept else "additional_content")
            for k, v in title_map.items()
        }
        print(f"  [normalizer] Columns reduced from {_original_count} "
              f"to {len(columns)} (max cap {_MAX_COLUMNS}).")

    if not title_map:
        print("  [normalizer] Warning: LLM returned no title mapping.")

    map_path.parent.mkdir(parents=True, exist_ok=True)
    with open(map_path, "w", encoding="utf-8") as f:
        json.dump({"columns": columns, "title_map": title_map},
                  f, ensure_ascii=False, indent=2)
    print(f"[normalizer] Column map saved to: {map_path}")
    print(f"[normalizer] Canonical columns ({len(columns)}): {', '.join(columns)}")

    return columns, title_map


def determine_columns_by_frequency(
    freq_data: dict,
    min_ratio: float = 0.15,
) -> tuple[list[str], dict[str, str]]:
    """Fallback without LLM: columns = most frequent titles above threshold.

    Returns:
        (columns, {}) — title_map is empty; classify_sections will use the
        per-document LLM or direct fallback.
    """
    total = freq_data.get("total_docs", 1)
    threshold = max(1, total * min_ratio)

    columns = [
        s["normalized_title"].strip()
        for s in freq_data.get("sections", [])
        if s["docs_con_seccion"] >= threshold
        and s["normalized_title"].strip() not in _STRUCTURAL
        and not s.get("es_estructural", False)
    ]

    if "additional_content" not in columns:
        columns.append("additional_content")

    return columns, {}


# ─── Main pipeline ────────────────────────────────────────────────────────────

def run_normalizer(
    control_path:  Path | str = "triage_control.json",
    output_dir:    Path | str = "output_normalizado",
    excel_path:    Path | str = "analyzed_pdfs.xlsx",
    backend:       str        = "none",
    model:         str | None = None,
    force:         bool       = False,
    min_col_ratio: float      = 0.15,
) -> None:
    """Run the full normalization pipeline.

    Args:
        control_path:  Path to triage_control.json.
        output_dir:    Folder for per-document intermediate JSON files.
        excel_path:    Output .xlsx path.
        backend:       "claude" | "ollama" | "none".
        model:         LLM model override.
        force:         If True, regenerate everything including the column map.
        min_col_ratio: Minimum document fraction for a column (no-LLM fallback).
    """
    control_path = Path(control_path)
    output_dir   = Path(output_dir)
    excel_path   = Path(excel_path)

    if not control_path.exists():
        print(f"[normalizer] {control_path} not found. Run run_triage() first.")
        return

    freq_path = control_path.parent / "section_freq.json"
    if not freq_path.exists():
        print(f"[normalizer] {freq_path} not found. Run run_triage() first.")
        return

    with open(freq_path, encoding="utf-8") as f:
        freq_data = json.load(f)

    # ── Determine columns ─────────────────────────────────────────────────────
    map_path = control_path.parent / "section_columns_map.json"
    client   = LLMClient(backend=backend, model=model) if backend != "none" else None

    if map_path.exists() and not force:
        with open(map_path, encoding="utf-8") as f:
            saved = json.load(f)
        columns   = saved.get("columns", [])
        title_map = saved.get("title_map", {})
        if "additional_content" not in columns:
            columns.append("additional_content")
        print(f"[normalizer] Column map loaded from: {map_path}")
        print(f"[normalizer] Canonical columns ({len(columns)}): {', '.join(columns)}")
    elif client is not None:
        columns, title_map = determine_columns_with_llm(freq_data, client, map_path)
    else:
        columns, title_map = determine_columns_by_frequency(freq_data, min_col_ratio)
        print("[normalizer] No LLM — columns determined by frequency.")
        print("  For better results, generate the manual prompt with:")
        print("    python normalize.py --export-prompt")
        print(f"  {', '.join(columns)}")

    with open(control_path, encoding="utf-8") as f:
        control: list[dict] = json.load(f)

    output_dir.mkdir(parents=True, exist_ok=True)

    if client is not None:
        print(f"[normalizer] LLM backend: {backend} / {model or 'default'}")
    else:
        print("[normalizer] No LLM: unmatched sections → additional_content")

    all_rows: list[dict[str, Any]] = []
    total = len(control)

    for i, entry in enumerate(control, start=1):
        filename  = entry.get("filename", "")
        json_path = Path(entry.get("json_path", ""))
        action    = entry.get("action", "skip")
        doc_type  = entry.get("doc_type", "")
        quality   = entry.get("quality_score")

        if not json_path.is_absolute():
            json_path = control_path.parent / json_path

        stem     = json_path.stem
        out_json = output_dir / f"{stem}.json"

        print(f"  [{i:>3}/{total}] {filename[:55]:<55} action={action}")

        if action not in _ACTIONS_TO_PROCESS:
            row: dict[str, Any] = {
                "filename":        filename,
                "code":            None,
                "product_name":    None,
                "doc_type":        None,
                "doc_type":       doc_type,
                "quality_score":   quality,
                "pages":           None,
                "action":           action,
            }
            for col in columns:
                row[col] = ""
            all_rows.append(row)
            continue

        if out_json.exists() and not force:
            with open(out_json, encoding="utf-8") as f:
                row = json.load(f)
            _meta = {"filename", "code", "product_name", "doc_type",
                     "quality_score", "pages", "action"}
            cached_cols = {k for k in row if k not in _meta}
            current_cols = set(columns)
            if not current_cols.issubset(cached_cols) or all(
                row.get(c, "") == "" for c in current_cols
            ):
                print(f"    ↺ Stale cache for {archivo[:45]} — reprocessing")
            else:
                for col in columns:
                    if col not in row:
                        row[col] = ""
                all_rows.append(row)
                continue

        if not json_path.exists():
            print(f"    ✗ JSON not found: {json_path}")
            continue

        with open(json_path, encoding="utf-8") as f:
            json_data = json.load(f)

        json_data["_doc_type"]      = doc_type
        json_data["_quality_score"] = quality

        try:
            row = build_row(json_data, client, action, columns, title_map)
        except Exception as e:
            print(f"    ✗ Error processing {archivo}: {e}")
            continue

        with open(out_json, "w", encoding="utf-8") as f:
            json.dump(row, f, ensure_ascii=False, indent=2)

        all_rows.append(row)

    print(f"\n[normalizer] {len(all_rows)} documents processed.")
    rows_to_excel(all_rows, excel_path, columns)
